before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
release:
  github:
    owner: GovtBlockchainAssoc
    name: daoctl
  draft: false
  prerelease: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
# signs:
#   artifacts: checksum
#   cmd: gpg2
